server:
  port: 9090
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
      properties:
        # 设置消费者重试策略
        max.poll.interval.ms: 30000
        retry.backoff.ms: 1000
        retry.max.attempts: 3
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3  #  重试次数
kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2
